package com.kevin.model;

import java.io.Serializable;
import java.util.Date;

public class Device implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.id
     *
     * @mbg.generated Thu May 09 14:35:21 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.device_serial_number
     *
     * @mbg.generated Thu May 09 14:35:21 CST 2019
     */
    private String deviceSerialNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.device_mac
     *
     * @mbg.generated Thu May 09 14:35:21 CST 2019
     */
    private String deviceMac;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.tenancy_id
     *
     * @mbg.generated Thu May 09 14:35:21 CST 2019
     */
    private Long tenancyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.create_at
     *
     * @mbg.generated Thu May 09 14:35:21 CST 2019
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVICE.update_at
     *
     * @mbg.generated Thu May 09 14:35:21 CST 2019
     */
    private Date updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DEVICE
     *
     * @mbg.generated Thu May 09 14:35:21 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.id
     *
     * @return the value of DEVICE.id
     *
     * @mbg.generated Thu May 09 14:35:21 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.id
     *
     * @param id the value for DEVICE.id
     *
     * @mbg.generated Thu May 09 14:35:21 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.device_serial_number
     *
     * @return the value of DEVICE.device_serial_number
     *
     * @mbg.generated Thu May 09 14:35:21 CST 2019
     */
    public String getDeviceSerialNumber() {
        return deviceSerialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.device_serial_number
     *
     * @param deviceSerialNumber the value for DEVICE.device_serial_number
     *
     * @mbg.generated Thu May 09 14:35:21 CST 2019
     */
    public void setDeviceSerialNumber(String deviceSerialNumber) {
        this.deviceSerialNumber = deviceSerialNumber == null ? null : deviceSerialNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.device_mac
     *
     * @return the value of DEVICE.device_mac
     *
     * @mbg.generated Thu May 09 14:35:21 CST 2019
     */
    public String getDeviceMac() {
        return deviceMac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.device_mac
     *
     * @param deviceMac the value for DEVICE.device_mac
     *
     * @mbg.generated Thu May 09 14:35:21 CST 2019
     */
    public void setDeviceMac(String deviceMac) {
        this.deviceMac = deviceMac == null ? null : deviceMac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.tenancy_id
     *
     * @return the value of DEVICE.tenancy_id
     *
     * @mbg.generated Thu May 09 14:35:21 CST 2019
     */
    public Long getTenancyId() {
        return tenancyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.tenancy_id
     *
     * @param tenancyId the value for DEVICE.tenancy_id
     *
     * @mbg.generated Thu May 09 14:35:21 CST 2019
     */
    public void setTenancyId(Long tenancyId) {
        this.tenancyId = tenancyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.create_at
     *
     * @return the value of DEVICE.create_at
     *
     * @mbg.generated Thu May 09 14:35:21 CST 2019
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.create_at
     *
     * @param createAt the value for DEVICE.create_at
     *
     * @mbg.generated Thu May 09 14:35:21 CST 2019
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVICE.update_at
     *
     * @return the value of DEVICE.update_at
     *
     * @mbg.generated Thu May 09 14:35:21 CST 2019
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVICE.update_at
     *
     * @param updateAt the value for DEVICE.update_at
     *
     * @mbg.generated Thu May 09 14:35:21 CST 2019
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVICE
     *
     * @mbg.generated Thu May 09 14:35:21 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Device other = (Device) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getDeviceSerialNumber() == null ? other.getDeviceSerialNumber() == null : this.getDeviceSerialNumber().equals(other.getDeviceSerialNumber()))
            && (this.getDeviceMac() == null ? other.getDeviceMac() == null : this.getDeviceMac().equals(other.getDeviceMac()))
            && (this.getTenancyId() == null ? other.getTenancyId() == null : this.getTenancyId().equals(other.getTenancyId()))
            && (this.getCreateAt() == null ? other.getCreateAt() == null : this.getCreateAt().equals(other.getCreateAt()))
            && (this.getUpdateAt() == null ? other.getUpdateAt() == null : this.getUpdateAt().equals(other.getUpdateAt()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVICE
     *
     * @mbg.generated Thu May 09 14:35:21 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDeviceSerialNumber() == null) ? 0 : getDeviceSerialNumber().hashCode());
        result = prime * result + ((getDeviceMac() == null) ? 0 : getDeviceMac().hashCode());
        result = prime * result + ((getTenancyId() == null) ? 0 : getTenancyId().hashCode());
        result = prime * result + ((getCreateAt() == null) ? 0 : getCreateAt().hashCode());
        result = prime * result + ((getUpdateAt() == null) ? 0 : getUpdateAt().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVICE
     *
     * @mbg.generated Thu May 09 14:35:21 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", deviceSerialNumber=").append(deviceSerialNumber);
        sb.append(", deviceMac=").append(deviceMac);
        sb.append(", tenancyId=").append(tenancyId);
        sb.append(", createAt=").append(createAt);
        sb.append(", updateAt=").append(updateAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}