swagger:
  enable: false

spring:
    datasource:
      primary:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        initialize: true #指定初始化数据源，是否用data.sql来初始化，默认: true
        name: cmmi
        url: jdbc:mysql://localhost:3306/viva_stanford
        username: root
        password: kevin123!
        maxActive: 20
        initialSize: 5
        maxWait: 12000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 12000
        testOnBorrow: false
        validationQuery: select 1
        filters: wall,stat
        removeAbandoned: true
        removeAbandonedTimeout: 300
      second:
              url: jdbc:mysql://xxx
              username: kevin
              password: kevin123!
              driver-class-name: com.mysql.jdbc.Driver
              druid:
                initial-size: 5
                min-idle: 1
                max-active: 10
                max-wait: 5000
                time-between-eviction-runs-millis: 60000
    thymeleaf:
      mode: HTML
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
      enabled: true


jedis:
  host: 127.0.0.1
  port: 6379

server:
  host: localhost
  port: 8080
  hosturl: localhost:8080
  tomcat:
    uri-encoding: utf-8
  debug: true

http:
  client:
    read-timeout: 2000
    connect-timeout: 2000
    qixi:
      url: https://preview.i.ai.mi.com


accessKeyId: xxxxx
accessKeySecret: xxxx

